### ISSUE TITLE
Consider rename from migen-formal to migen-axi or migen-zynq

### ISSUE THREAD

**Issue by mithro** [peteut/migen-axi#7]
It seems like there are currently mutiple efforts to interface Migen and LiteX with AXI + Zynq boards.

It would make this project a lot more findable if it was called something like `migen-zynq` or `migen-axi`.

Keep up the great work!

**Comment by peteut** [comment]
@mithro agreed, maybe `migen-axi` as [Intel SoCs](https://www.altera.com/products/soc/overview.html) support may be added later on?

**Comment by mithro** [comment]
`migen-axi` sounds good to me!

**Comment by peteut** [comment]
Fixed by 09b5c2ef8327b7ef592d65d8f668f35006d519a5.
